include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    deprecated_member_use: false
    use_build_context_synchronously: false
    use_super_parameters: false
    library_private_types_in_public_api: false